In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [90]:
class NN_1:
    def __init__(self, d_input, width, d_output):
        
        self.weights = {
                        'h1': torch.randn((width, d_input), requires_grad=True), 
                        'out': torch.randn((d_output, width), requires_grad=True)
                    }
        
        self.biases = {
                        'h1': torch.randn((width), requires_grad=True), 
                        'out': torch.randn((d_output), requires_grad=True)
                    }
        
        self.parameters = []
        for i in range(len(self.weights) * 2):
            if i % 2 == 0:
                self.parameters.append(list(self.weights.values())[int(i / 2)])
            else:
                self.parameters.append(list(self.biases.values())[int(i / 2)])

        
    def forward(self, x):
        x = torch.tanh((x @ torch.transpose(self.weights['h1'], 0, 1)) + self.biases['h1'])
        x = (x @ torch.transpose(self.weights['out'], 0, 1)) + self.biases['out']
        
        return x
    
class NN_2(nn.Module):
    def __init__(self, d_input, width, d_output):
        super().__init__()
        
        self.fc1 = nn.Linear(d_input, width)
        self.fc2 = nn.Linear(width, d_output)
        
    def forward(self, x):
        x = torch.tanh(self.fc1(x))
        x = self.fc2(x)
        
        return x

In [115]:
print(torch.zeros(1,2).normal_(0, 1, generator=torch.manual_seed(0)))

print(torch.normal(mean=torch.zeros(2), std=torch.ones(2), generator=torch.manual_seed(0)))

tensor([[ 1.5410, -0.2934]])
tensor([ 1.5410, -0.2934])


In [93]:
x = torch.Tensor([[20., 30.], [10., 40.]])
print(x.shape)
net_1 = NN_1(2, 2, 1)
print(net_1.weights['h1'].shape)
print(net_1.forward(x))

y = torch.Tensor([[2.], [1.]])

loss = torch.sum(y - net_1.forward(x))

loss.backward()

torch.Size([2, 2])
torch.Size([2, 2])
tensor([[-1.5383],
        [-1.6069]], grad_fn=<AddBackward0>)


In [117]:
net_2 = NN_2(2, 2, 1)
# x = torch.Tensor([[20.], [10.]])
for p2, p1 in zip(net_2.parameters(), net_1.parameters):
    print(p2)
    p2.data = p1
    
print(net_2.forward(x))
 
loss = torch.sum(y - net_2.forward(x))

loss.backward()
    
for p2, p1 in zip(net_2.parameters(), net_1.parameters):
    print(p2.grad, p1.grad)


Parameter containing:
tensor([[-0.4683, -0.2915],
        [ 0.0262,  0.2795]], requires_grad=True)
Parameter containing:
tensor([ 0.4243, -0.4794], requires_grad=True)
Parameter containing:
tensor([[-0.3079,  0.2568]], requires_grad=True)
Parameter containing:
tensor([0.5872], requires_grad=True)
tensor([[-1.5383],
        [-1.6069]], grad_fn=<AddmmBackward>)
tensor([[2.6045, 3.9067],
        [0.0000, 0.0000]]) tensor([[2.6045, 3.9067],
        [0.0000, 0.0000]])
tensor([0.1302, 0.0000]) tensor([0.1302, 0.0000])
tensor([[-1.8964,  2.0000]]) tensor([[-1.8964,  2.0000]])
tensor([-2.]) tensor([-2.])


In [5]:
a = [1, 2, 3]

b = [4, 5, 6]

c = [7, 8, 9]

# for i, (aa, (bb, cc)) in enumerate(zip(a, zip(b, c))):
#     print(aa, bb, cc)

l = []
for i in range(len(a) * 2):
    if i % 2 == 0:
        print(int(i / 2))
        l.append(a[int(i / 2)])
    else:
        l.append(b[int(i / 2)])

print(l)

0
1
2
[1, 4, 2, 5, 3, 6]


In [7]:
ad = dict(zip(['a', 'b', 'c'], a))

bd = dict(zip(['a', 'b', 'c'], b))

lk = []
lv = []
for i in range(len(ad) * 2):
    if i % 2 == 0:
        lk.append(list(ad.keys())[int(i / 2)])
        lv.append(list(ad.values())[int(i / 2)])
    else:
        lk.append(list(bd.keys())[int(i / 2)])
        lv.append(list(bd.values())[int(i / 2)])
        
params = dict(zip(lk, lv))
print(params)

{'a': 4, 'b': 5, 'c': 6}


In [64]:
print(list(ad.keys())*2)

['a', 'b', 'c', 'a', 'b', 'c']


In [61]:
import torch
import torch.nn.functional as F
from torch import nn

# define the network class
class MyNetwork(nn.Module):
    def __init__(self):
        # call constructor from superclass
        super().__init__()
        
        # define network layers
        self.fc1 = nn.Linear(16, 12)
        self.fc2 = nn.Linear(12, 10)
        self.fc3 = nn.Linear(10, 1)
        
    def forward(self, x):
        # define forward pass
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

# instantiate the model
model = MyNetwork()

# print model architecture
print(model)

MyNetwork(
  (fc1): Linear(in_features=16, out_features=12, bias=True)
  (fc2): Linear(in_features=12, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)


In [12]:
from torch import nn

# define model architecture
model = nn.Sequential(
    nn.Linear(16, 12),
    nn.ReLU(),
    nn.Linear(12, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.Sigmoid()
)

# print model architecture
print(model)

Sequential(
  (0): Linear(in_features=16, out_features=12, bias=True)
  (1): ReLU()
  (2): Linear(in_features=12, out_features=10, bias=True)
  (3): ReLU()
  (4): Linear(in_features=10, out_features=1, bias=True)
  (5): Sigmoid()
)


In [13]:
print(model[0], model[0].weight)

Linear(in_features=16, out_features=12, bias=True) Parameter containing:
tensor([[ 0.2065, -0.0631,  0.0714,  0.2364,  0.0261,  0.0686, -0.0647,  0.0578,
         -0.1182,  0.0092,  0.1839,  0.1092, -0.2156, -0.0449,  0.2216, -0.2389],
        [-0.2302,  0.0407,  0.2363,  0.1472, -0.0643, -0.2347,  0.2033,  0.0621,
          0.0259,  0.1800,  0.0557, -0.2329, -0.0376,  0.2089,  0.0487, -0.0672],
        [ 0.0881,  0.1264,  0.0358, -0.0866,  0.0249,  0.2120, -0.0980,  0.0018,
         -0.0894, -0.0676,  0.1094, -0.2233, -0.1025, -0.0570, -0.0228,  0.0078],
        [ 0.0427, -0.1092,  0.1874,  0.1790,  0.1495,  0.0125, -0.1557, -0.0048,
          0.0672,  0.0308, -0.2470, -0.2346,  0.0121, -0.0025,  0.1636, -0.0887],
        [-0.0802,  0.1188, -0.1589, -0.0563, -0.1991, -0.0490, -0.1646, -0.0328,
         -0.1614,  0.1260,  0.1872, -0.1201, -0.0663, -0.0315,  0.0454, -0.0108],
        [-0.1953, -0.0577,  0.1354,  0.0608, -0.0005,  0.2087, -0.0103, -0.1484,
         -0.0593,  0.2160,  0.1