In [5]:
import torch
import torch.nn.functional as F

# generating some random features
features = torch.randn(1, 16) 

# define the weights
W1 = torch.randn((16, 12), requires_grad=True)
W2 = torch.randn((12, 10), requires_grad=True)
W3 = torch.randn((10, 1), requires_grad=True)

# define the bias terms
B1 = torch.randn((12), requires_grad=True)
B2 = torch.randn((10), requires_grad=True)
B3 = torch.randn((1), requires_grad=True)

# calculate hidden and output layers
h1 = F.relu((features @ W1) + B1)
h2 = F.relu((h1 @ W2) + B2)
output = torch.sigmoid((h2 @ W3) + B3)

In [102]:
class MyNetwork:
    def __init__(self, d_input, width, d_output):
        self.W1 = torch.randn((d_input, width), requires_grad=True)
        self.W2 = torch.randn((width, d_output), requires_grad=True)
        
        self.B1 = torch.randn((width), requires_grad=True)
        self.B2 = torch.randn((d_output), requires_grad=True)
        
    def forward(self, x):
        # define forward pass
        x = torch.tanh((x @ self.W1) + self.B1)
        x = (x @ self.W2) + self.B2
        return x
    
# define the network class
class MyNetwork_2(nn.Module):
    def __init__(self, d_input, width, d_output):
        # call constructor from superclass
        super().__init__()
        
        # define network layers
        self.fc1 = nn.Linear(d_input, width)
        self.fc2 = nn.Linear(width, d_output)
        
    def forward(self, x):
        # define forward pass
        x = torch.tanh(self.fc1(x))
        x = self.fc2(x)
        return x

In [107]:
net = MyNetwork(1, 2, 1)

# print(net.W1)
print(net.forward(x))

net.W1 = torch.tensor([[0.7682, 0.7330]], requires_grad=True)

net.B1 = torch.tensor([0.0610, 0.6632], requires_grad=True)

net.W2 = torch.tensor([[-0.2765], [-0.4346]], requires_grad=True)

net.B2 = torch.tensor([0.6827], requires_grad=True)

# print(net.W1)

x = torch.Tensor([20.])

print(net.forward(x))



tensor([0.7193], grad_fn=<AddBackward0>)
tensor([-0.0284], grad_fn=<AddBackward0>)


In [108]:
# net_2 = MyNetwork_2(1, 2, 1)

print(list(net_2.parameters()))

print(list(net_2.fc1.weight))
print(list(net_2.fc1.bias))

print(list(net_2.fc2.weight))
print(list(net_2.fc2.bias))

x = torch.Tensor([20.])

print(net_2.forward(x))

[Parameter containing:
tensor([[0.7682],
        [0.7330]], requires_grad=True), Parameter containing:
tensor([0.0610, 0.6632], requires_grad=True), Parameter containing:
tensor([[-0.2765, -0.4346]], requires_grad=True), Parameter containing:
tensor([0.6827], requires_grad=True)]
[tensor([0.7682], grad_fn=<UnbindBackward>), tensor([0.7330], grad_fn=<UnbindBackward>)]
[tensor(0.0610, grad_fn=<UnbindBackward>), tensor(0.6632, grad_fn=<UnbindBackward>)]
[tensor([-0.2765, -0.4346], grad_fn=<UnbindBackward>)]
[tensor(0.6827, grad_fn=<UnbindBackward>)]
tensor([-0.0284], grad_fn=<AddBackward0>)


In [11]:
import torch
import torch.nn.functional as F
from torch import nn

# define the network class
class MyNetwork(nn.Module):
    def __init__(self):
        # call constructor from superclass
        super().__init__()
        
        # define network layers
        self.fc1 = nn.Linear(16, 12)
        self.fc2 = nn.Linear(12, 10)
        self.fc3 = nn.Linear(10, 1)
        
    def forward(self, x):
        # define forward pass
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

# instantiate the model
model = MyNetwork()

# print model architecture
print(model)

MyNetwork(
  (fc1): Linear(in_features=16, out_features=12, bias=True)
  (fc2): Linear(in_features=12, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)


In [12]:
from torch import nn

# define model architecture
model = nn.Sequential(
    nn.Linear(16, 12),
    nn.ReLU(),
    nn.Linear(12, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.Sigmoid()
)

# print model architecture
print(model)

Sequential(
  (0): Linear(in_features=16, out_features=12, bias=True)
  (1): ReLU()
  (2): Linear(in_features=12, out_features=10, bias=True)
  (3): ReLU()
  (4): Linear(in_features=10, out_features=1, bias=True)
  (5): Sigmoid()
)


In [13]:
print(model[0], model[0].weight)

Linear(in_features=16, out_features=12, bias=True) Parameter containing:
tensor([[ 0.2065, -0.0631,  0.0714,  0.2364,  0.0261,  0.0686, -0.0647,  0.0578,
         -0.1182,  0.0092,  0.1839,  0.1092, -0.2156, -0.0449,  0.2216, -0.2389],
        [-0.2302,  0.0407,  0.2363,  0.1472, -0.0643, -0.2347,  0.2033,  0.0621,
          0.0259,  0.1800,  0.0557, -0.2329, -0.0376,  0.2089,  0.0487, -0.0672],
        [ 0.0881,  0.1264,  0.0358, -0.0866,  0.0249,  0.2120, -0.0980,  0.0018,
         -0.0894, -0.0676,  0.1094, -0.2233, -0.1025, -0.0570, -0.0228,  0.0078],
        [ 0.0427, -0.1092,  0.1874,  0.1790,  0.1495,  0.0125, -0.1557, -0.0048,
          0.0672,  0.0308, -0.2470, -0.2346,  0.0121, -0.0025,  0.1636, -0.0887],
        [-0.0802,  0.1188, -0.1589, -0.0563, -0.1991, -0.0490, -0.1646, -0.0328,
         -0.1614,  0.1260,  0.1872, -0.1201, -0.0663, -0.0315,  0.0454, -0.0108],
        [-0.1953, -0.0577,  0.1354,  0.0608, -0.0005,  0.2087, -0.0103, -0.1484,
         -0.0593,  0.2160,  0.1